### ISSUE TITLE
[1.16.1] Weird Error

### ISSUE THREAD

**Issue by ClockworkFountain** [SmellyModder/Seeker-Compass#6] opened 2020-10-19 23:10 UTC
Occurs in early loading stages of boot-up
[Latest.log](https://pastebin.com/zJVX0QUc)
[Crash Report](https://pastebin.com/vizL5s3E)

**Comment by SmellyModder** [comment] 2020-12-03 04:25
This doesn't look like an issue caused by this mod.
Have you tried removing Seeker Compass and seeing if the crash still happens?

**Comment by ClockworkFountain** [comment] 2020-12-04 05:13
I’d have to check, it’s been a while since I’ve tried to boot up that pack due to the newer versions of forge.

**Comment by electric-ajax** [comment] 2021-04-28 12:30
I have this exact issue. When it finishes loading it says that there's "missing files" for the mod. I tried without it and it worked fine.

**Comment by SmellyModder** [comment] 2021-06-30 16:45
Fixed in commit https://github.com/SmellyModder/Seeker-Compass/commit/03dc913bdc254942bdcb19c84ffc4bad8771a96d
The new version on Curseforge includes this fix.

**Closed as completed by SmellyModder** 2021-06-30 16:45 UTC
Labels: Bug
